CREATE DATABASE PTDL
GO    
USE PTDL   
GO

CREATE TABLE KHACHHANG(
    MA_KH CHAR(5) PRIMARY KEY,
    TEN_KH NVARCHAR(100),
    CMND VARCHAR(50),
    DIA_CHI NVARCHAR(100),
    SDT CHAR(10),
    Email VARCHAR(50),
    Fax VARCHAR(10),
    NGAY_DEN DATETIME,
    SO_DEM_LUU_TRU INT,
    LOAI_PHONG varchar(50),
    YEU_CAU_DB CHAR(5),
    LOAI_KH VARCHAR(50),
    CHUC_VU VARCHAR(50),
    TRANG_THAI_DAT_PHONG NVARCHAR(50)
);



CREATE TABLE DOAN (
   MA_DOAN CHAR(5) PRIMARY KEY,
   TEN_DOAN NVARCHAR(255) NOT NULL,
   TEN_NGUOI_DK NVARCHAR(255),
   NGAY_DEN DATE,
   SO_NGUOI INT,
   SO_DEM_LUU_TRU INT
);
CREATE TABLE FEEDBACK (
   MA_FB CHAR(5) PRIMARY KEY,
   TEN_FB NVARCHAR(255) NOT NULL,
   MIEU_TA_FB NVARCHAR(255),
   LOAI_FB NVARCHAR(255),
   DANH_GIA NVARCHAR(255),
   MA_KH CHAR(5)
);
CREATE TABLE CONGTYDULICH (
   MA_CTY CHAR(5) PRIMARY KEY,
   TEN_CTY NVARCHAR(255) NOT NULL,
   TEN_NGUOI_DAI_DIEN NVARCHAR(255),
   DIA_CHI NVARCHAR(255)
);

CREATE TABLE YEUCAUDACBIET (
   MA_YCDC CHAR(5) PRIMARY KEY,
   MA_KH CHAR(5),
   TEN_YCDC NVARCHAR(255) NOT NULL
);


CREATE TABLE PHONG (
    MA_PHONG CHAR(5) PRIMARY KEY,
    TEN_PHONG NVARCHAR(100),
    SO_LUONG_DAP_UNG INT,
    LOAI NVARCHAR(30),
    TRANG_THAI BIT,
    GIA INT
);
CREATE TABLE NHANVIEN(
    MA_NV CHAR(5) PRIMARY KEY,
    TEN_NV NVARCHAR(100) ,
    CHUC_VU NVARCHAR(50),
    EMAIL  VARCHAR(50),
    GIOI_TINH VARCHAR(3),
    SDT CHAR(10),
    CMND VARCHAR(50),
    NGAY_SINH DATETIME,
    NGAY_THAM_GIA DATETIME,
    DIA_CHI DATETIME,
    LUONG FLOAT
);

CREATE TABLE PHIEUDANGKYVANCHUYEN(
    MA_PHIEUDANGKYVANCHUYEN CHAR(5) PRIMARY KEY,
    MA_PHONG CHAR(5),
    MA_KH CHAR(5),
    MA_NV CHAR(5),
    NGAY_TAO DATETIME,
    SO_LUONG INT
);

CREATE TABLE PHIEUDATPHONG(
    MA_PHIEU_DP CHAR(5) PRIMARY KEY,
    MA_KH CHAR(5),
    MA_NV CHAR(5),
    NGAY_DAT DATETIME,
    TONG_TIEN FLOAT,
    TIEN_COC FLOAT,
    LOAIPHONG NVARCHAR(20),
    NGAY_TRA_PHONG DATETIME
);

CREATE TABLE PHANCONGDONVESINH(
    MA_NV CHAR(5),
    MA_PHONG CHAR(5),
    NGAY_LAM DATETIME,
    PRIMARY KEY(MA_NV, MA_PHONG)
);


CREATE TABLE PHANPHONG(
    MA_NVQL CHAR (5),
    MA_PHIEU_DP CHAR(5),
    MA_PHONG CHAR(5),
    NGAY_PHAN_PHONG DATETIME,
    NGAY_NHAN DATETIME
    PRIMARY KEY(MA_PHONG, MA_PHIEU_DP)
);

CREATE TABLE DICHVUKHACHSAN(
    MA_DV CHAR(5) PRIMARY KEY,
    TENDICHVU NVARCHAR(50),
    GIA FLOAT,
    DIADIEM NVARCHAR(50),
);

CREATE TABLE GOIDICHVU(
    MA_GOIDV CHAR(5) PRIMARY KEY,
    MA_PHIEU_DP CHAR(5),
    GIA FLOAT,
);

CREATE TABLE PHIEUDANGKYDICHVU(
    MA_PHIEUDV CHAR(5) PRIMARY KEY,
    NGAY_DANG_KY DATETIME,
    TONG_TIEN FLOAT,
    GHI_NHAN_SU_DUNG BIT,
    NGAY_SU_DUNG DATETIME,
    MA_PHIEU_DP CHAR(5),
    MA_NV CHAR(5),
    MA_DV CHAR(5)
)


CREATE TABLE CHITIETGDV(
    MA_GOIDV CHAR(5),
    MA_DV CHAR(5),
    GIAMGIA INT, -- PHAN TRAM GIAM
    PRIMARY KEY(MA_GOIDV, MA_DV) 
);

CREATE TABLE CHITIETDOAN(
    MA_KH CHAR(5),
    MA_DOAN CHAR(5),
    SO_NGUOI INT,
    PRIMARY KEY(MA_KH, MA_DOAN)
);
CREATE TABLE CHITIETDULICH(
    MA_KH CHAR(5),
    MA_CTY CHAR(5),
    DIADIEM NVARCHAR(50),
    NGAY_DEN_KHACH_SAN DATE,
    PRIMARY KEY(MA_KH, MA_CTY)
);

CREATE TABLE CHITIETTHANHTOANDV(
    MA_HD CHAR(5),
    MA_PHIEUDV CHAR(5),
    DON_GIA FLOAT,
    MA_KETOAN CHAR(5),
    PRIMARY KEY(MA_HD, MA_PHIEUDV)
);

CREATE TABLE HOADON(
    MA_HD CHAR(5) PRIMARY KEY, 
    NGAY_LAP DATETIME,
    TIEN_DV FLOAT,
    TIEN_PHATSINH FLOAT,
    TONG_TIEN FLOAT,
    NHAN_VIEN_LAP CHAR(5),    
    MA_PHIEU_DP CHAR(5),
);
 

CREATE TABLE PHIEUKIEMTRAPHONG(
    MA_PHIEUKT CHAR(5) PRIMARY KEY,
    THOI_GIAN_LAP DATETIME,
    TRANG_THAI NVARCHAR(20),
    TONG_TIEN_BOI_THUONG FLOAT,
    MA_NV CHAR(5),
    MA_HD CHAR(5)
);

CREATE TABLE CHITIETPHIEUKIEMTRAPHONG(
    MA_PHIEUKT CHAR(5),
    STT INT,
    CHI_TIET_HUHAI NVARCHAR(50),
    GIA_BOI_THUONG INT,
    PRIMARY KEY(MA_PHIEUKT,STT)
);

CREATE TABLE DONVILUUHANH(
    MA_DV CHAR(5) PRIMARY KEY,
    TEN_DV NVARCHAR(50),
    PHI_GT FLOAT
);


CREATE TABLE TOURDULICH(
    MA_TOUR CHAR(5) PRIMARY KEY,
    TEN_TOUR CHAR(5),
    MOTA NVARCHAR(50),
    GIA FLOAT,
    MA_DV CHAR(5)
    
)

CREATE TABLE PHIEUDKTOUR(
    MA_P CHAR(5) PRIMARY KEY,
    NGAYDANGKY DATE,
    TENNGUOIDK NVARCHAR(50),
    THOIGIANKHOIHANG DATETIME,
    SONGUOITHAMGIA INT,
    DICHVUDUADON NVARCHAR(50),
    TRANGTHAI NVARCHAR(20),
    MA_TOUR CHAR(5),
    MA_KH CHAR(5),
    MA_NV CHAR(5)
)

CREATE TABLE DONVIVANCHUYEN(
    MA_DONVIVANCHUYEN CHAR(5) PRIMARY KEY,
    TEN_DONVI CHAR(5),
    NGAY_GIOITHIEU DATE,
    PHI_GIOITHIEU FLOAT 
)



CREATE TABLE DONDATXE(
    MA_DON_DAT_XE CHAR(5) PRIMARY KEY,
    MA_KH CHAR(5),
    MA_DONVIVANCHUYEN CHAR(5),
    MA_NV CHAR(5),
    BANG_SO_XE NVARCHAR(10),
    NGAY_DAT NVARCHAR(10),
)


CREATE TABLE TAIKHOAN(
    MA_TAIKHOAN CHAR(5) PRIMARY KEY,
    TEN_TAIKHOAN NVARCHAR(50),
    MATKHAU NVARCHAR(50),
    MA_NV CHAR(5)        
)

-----------------------------------------------------------------------------
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TAIKHOAN_NHANVIEN
FOREIGN KEY(MA_NV) REFERENCES NHANVIEN(MA_NV);

-----------------------------------------------------------------------------
ALTER TABLE PHIEUDATPHONG
ADD CONSTRAINT FK_PHIEUDATPHONG_KHACHHANG
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH);

ALTER TABLE PHIEUDATPHONG
ADD CONSTRAINT FK_PHIEUDATPHONG_NHANVIEN
FOREIGN KEY(MA_NV) REFERENCES NHANVIEN(MA_NV);
--------------------------------------------------------------------------------------
ALTER TABLE PHANPHONG
ADD CONSTRAINT FK_PHANPHONG_NHANVIEN
FOREIGN KEY(MA_NVQL) REFERENCES NHANVIEN(MA_NV);

ALTER TABLE PHANPHONG
ADD CONSTRAINT FK_PHANPHONG_PHIEUDATPHONG
FOREIGN KEY(MA_PHIEU_DP) REFERENCES PHIEUDATPHONG(MA_PHIEU_DP);

ALTER TABLE PHANPHONG
ADD CONSTRAINT FK_PHANPHONG_PHONG
FOREIGN KEY(MA_PHONG) REFERENCES PHONG(MA_PHONG);
--------------------------------------------------------------------------------------------

ALTER TABLE CHITIETDOAN
ADD CONSTRAINT FK_CHITIETDOAN_DOAN
FOREIGN KEY(MA_DOAN) REFERENCES DOAN(MA_DOAN);

ALTER TABLE CHITIETDOAN
ADD CONSTRAINT FK_CHITIETDOAN_KH
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH);
--------------------------------------------------------------------------
ALTER TABLE FEEDBACK
ADD CONSTRAINT FK_FEEDBACK_KHACHHANG
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH);

ALTER TABLE CHITIETGDV
ADD CONSTRAINT FK_CHITIETGDV_GOIDV
FOREIGN KEY(MA_GOIDV) REFERENCES GOIDICHVU(MA_GOIDV);

ALTER TABLE CHITIETGDV
ADD CONSTRAINT FK_CHITIETGDV_DVKHACHSAN
FOREIGN KEY(MA_DV) REFERENCES DICHVUKHACHSAN(MA_DV);


ALTER TABLE CHITIETPHIEUKIEMTRAPHONG
ADD CONSTRAINT FK_CHITIETPHIEUKIEMTRAPHONG_PHIEUKTPHONG
FOREIGN KEY(MA_PHIEUKT) REFERENCES PHIEUKIEMTRAPHONG(MA_PHIEUKT) 


ALTER TABLE PHIEUKIEMTRAPHONG
ADD CONSTRAINT FK_PHIEUKIEMTRAPHONG_BUONGPHONG
FOREIGN KEY(MA_NV) REFERENCES NHANVIEN(MA_NV) 


--------------------------------- check done ---------------------------------------
ALTER TABLE CHITIETDULICH
ADD CONSTRAINT FK_CHITIETDULICH_KH
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH) 

ALTER TABLE CHITIETDULICH
ADD CONSTRAINT FK_CHITIETDULICH_CTYDULICH
FOREIGN KEY(MA_CTY) REFERENCES CONGTYDULICH(MA_CTY) 

-------------------------------------check done-------------------------------------------------
ALTER TABLE DONDATXE
ADD CONSTRAINT FK_DONDATXE_KHACHHANG
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH) 

ALTER TABLE DONDATXE
ADD CONSTRAINT FK_DONDATXE_NHANVIEN
FOREIGN KEY(MA_NV) REFERENCES NHANVIEN(MA_NV) 

ALTER TABLE DONDATXE
ADD CONSTRAINT FK_DONDATXE_DONVIVANCHUYEN
FOREIGN KEY(MA_DONVIVANCHUYEN) REFERENCES DONVIVANCHUYEN(MA_DONVIVANCHUYEN) 

------------------------------------------------------check done---------------------------------
ALTER TABLE PHIEUDKTOUR
ADD CONSTRAINT FK_PHIEUDKTOUR_TOURDULICH
FOREIGN KEY (MA_TOUR) REFERENCES TOURDULICH(MA_TOUR)

ALTER TABLE PHIEUDKTOUR
ADD CONSTRAINT FK_PHIEUDKTOUR_NHANVIEN
FOREIGN KEY (MA_NV) REFERENCES NHANVIEN(MA_NV)

ALTER TABLE PHIEUDKTOUR
ADD CONSTRAINT FK_PHIEUDKTOUR_KHACHHANG
FOREIGN KEY (MA_KH) REFERENCES KHACHHANG(MA_KH) 

-----------------------------------------------check done--------------------------------------------------------


ALTER TABLE YEUCAUDACBIET
ADD CONSTRAINT FK_YEUCAUDACBIET_kh
FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH) 


------------------------------------ CHECK DONE---------------------------------------------------------------
ALTER TABLE PHIEUDANGKYVANCHUYEN
ADD CONSTRAINT FK_PHIEUDANGKYVANCHUYEN_NHANVIEN 
FOREIGN KEY (MA_NV) REFERENCES NHANVIEN(MA_NV)

ALTER TABLE PHIEUDANGKYVANCHUYEN
ADD CONSTRAINT FK_PHIEUDANGKYVANCHUYEN_PHONG 
FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)

ALTER TABLE PHIEUDANGKYVANCHUYEN
ADD CONSTRAINT FK_PHIEUDANGKYVANCHUYEN_KHACHHANG
FOREIGN KEY (MA_KH) REFERENCES KHACHHANG(MA_KH)


-------------------------CHECK DONE-------------------------

ALTER TABLE PHANCONGDONVESINH
ADD CONSTRAINT FK_PHANCONGDONVESINH_NHANVIEN
FOREIGN KEY (MA_NV) REFERENCES NHANVIEN(MA_NV)

ALTER TABLE PHANCONGDONVESINH
ADD CONSTRAINT FK_PHANCONGDONVESINH_PHONG
FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG)


---------------------------CHECK DONE----------------------

ALTER TABLE TOURDULICH
ADD CONSTRAINT FK_TOURDULICH_LUHANH
FOREIGN KEY (MA_DV) REFERENCES DONVILUUHANH(MA_DV)

-----------------------------------------------------------------
--          HOA DON         --
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_NHANVIEN
FOREIGN KEY(NHAN_VIEN_LAP) REFERENCES NHANVIEN(MA_NV)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_PHIEUDATPHONG
FOREIGN KEY(MA_PHIEU_DP) REFERENCES PHIEUDATPHONG(MA_PHIEU_DP)

ALTER TABLE PHIEUKIEMTRAPHONG
ADD CONSTRAINT FK_PHIEUKTP_HOADON
FOREIGN KEY(MA_HD) REFERENCES HOADON(MA_HD)

ALTER TABLE CHITIETTHANHTOANDV
ADD CONSTRAINT FK_CTTTDV_HOADON
FOREIGN KEY(MA_HD) REFERENCES HOADON(MA_HD)

ALTER TABLE CHITIETTHANHTOANDV
ADD CONSTRAINT FK_CTTTDV_PDKDV
FOREIGN KEY(MA_PHIEUDV) REFERENCES PHIEUDANGKYDICHVU(MA_PHIEUDV)

ALTER TABLE CHITIETTHANHTOANDV
ADD CONSTRAINT FK_CTTTDV_NV
FOREIGN KEY(MA_KETOAN) REFERENCES NHANVIEN(MA_NV)

------------------------------CHECK DONE --------------------------
ALTER TABLE PHIEUDANGKYDICHVU
ADD CONSTRAINT FK_PHIEUDANGKYDICHVU_NHANVIEN
FOREIGN KEY (MA_NV) REFERENCES NHANVIEN(MA_NV)


ALTER TABLE PHIEUDANGKYDICHVU
ADD CONSTRAINT FK_PHIEUDANGKYDICHVU_DICHVU
FOREIGN KEY (MA_DV) REFERENCES DICHVUKHACHSAN(MA_DV)


ALTER TABLE PHIEUDANGKYDICHVU
ADD CONSTRAINT FK_PHIEUDANGKYDICHVU_PHIEUDATPHONG
FOREIGN KEY (MA_PHIEU_DP) REFERENCES PHIEUDATPHONG(MA_PHIEU_DP)

----------------------------check done--------------------------

ALTER TABLE GOIDICHVU
ADD CONSTRAINT FK_GOIDICHVU_PHIEUDATPHONG
FOREIGN KEY (MA_PHIEU_DP) REFERENCES PHIEUDATPHONG(MA_PHIEU_DP)


---------------------------------------------------------------
