import Head from "next/head";
import React from "react";

type Props = {
   children?: React.ReactNode;
};

const EmptyLayout = (props: Props) => {
   return (
      <>
         <Head>
            <title>Lazy Days</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />

            <link rel="icon" href="/favicon.ico" />
            <link
               href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css"
               rel="stylesheet"
            />
            <script
               src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"
               async
            />
         </Head>
         <main>{props.children}</main>
      </>
   );
};

export default EmptyLayout;
